ALTER TABLE "Workspace"
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'PKR',
ADD COLUMN "lowStockMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN "expiryAlertDays" INTEGER NOT NULL DEFAULT 7;
