import { prisma } from "../db/prisma.js";
import { logger } from "./logger.js";

const DEFAULT_PLANS = [
  {
    name: "Free",
    code: "FREE",
    description: "Everything you need to replace your spreadsheet and get started.",
    monthlyPrice: 0,
    annualPrice: 0,
    currency: "$",
    trialDays: 0,
    maxUsers: 3,
    maxLocations: 1,
    maxItems: 50,
    maxSuppliers: null,
    enableExpiryTracking: true,
    enableBarcodeScanning: false,
    enableReports: true,
    enableAdvancedReports: false,
    enablePurchases: false,
    enableSuppliers: false,
    enableTeamManagement: false,
    enableCustomRoles: false,
    enableEmailAlerts: false,
    enableDailyOps: false,
    ctaText: "Start Free",
    isPublic: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: "Basic",
    code: "STARTER",
    description: "For growing teams who need real inventory control across multiple locations.",
    monthlyPrice: 19,
    annualPrice: 190,
    currency: "$",
    trialDays: 0,
    maxUsers: 10,
    maxLocations: 5,
    maxItems: 500,
    maxSuppliers: null,
    enableExpiryTracking: true,
    enableBarcodeScanning: true,
    enableReports: true,
    enableAdvancedReports: false,
    enablePurchases: true,
    enableSuppliers: true,
    enableTeamManagement: true,
    enableCustomRoles: false,
    enableEmailAlerts: true,
    enableDailyOps: true,
    ctaText: "Choose Basic",
    isPublic: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: "Pro",
    code: "PRO",
    description: "Unlimited everything. Advanced analytics, custom roles, and full team control.",
    monthlyPrice: 49,
    annualPrice: 490,
    currency: "$",
    trialDays: 0,
    maxUsers: null,
    maxLocations: null,
    maxItems: null,
    maxSuppliers: null,
    enableExpiryTracking: true,
    enableBarcodeScanning: true,
    enableReports: true,
    enableAdvancedReports: true,
    enablePurchases: true,
    enableSuppliers: true,
    enableTeamManagement: true,
    enableCustomRoles: true,
    enableEmailAlerts: true,
    enableDailyOps: true,
    ctaText: "Choose Pro",
    isPublic: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: "Business",
    code: "BUSINESS",
    description: "Enterprise-grade inventory management with dedicated support and custom onboarding.",
    monthlyPrice: 0,
    annualPrice: 0,
    currency: "$",
    trialDays: 0,
    maxUsers: null,
    maxLocations: null,
    maxItems: null,
    maxSuppliers: null,
    enableExpiryTracking: true,
    enableBarcodeScanning: true,
    enableReports: true,
    enableAdvancedReports: true,
    enablePurchases: true,
    enableSuppliers: true,
    enableTeamManagement: true,
    enableCustomRoles: true,
    enableEmailAlerts: true,
    enableDailyOps: true,
    ctaText: "Contact Sales",
    priceDisplayMode: "CUSTOM" as const,
    isPublic: true,
    isActive: true,
    sortOrder: 4,
  },
];

export async function seedDefaultPlansIfEmpty(): Promise<void> {
  try {
    logger.info("[SEED] Syncing default plans");

    for (const plan of DEFAULT_PLANS) {
      const { code, ...rest } = plan;
      await prisma.plan.upsert({
        where: { code },
        update: rest,
        create: plan,
      });
    }

    logger.info("[SEED] Default plans synced: FREE, STARTER(Basic), PRO, BUSINESS");
  } catch (err) {
    logger.error("[SEED] Failed to seed default plans", { error: String(err) });
  }
}
