// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-redesign/CompactTwoColumn.tsx": () => import("../components/mockups/dashboard-redesign/CompactTwoColumn.tsx"),
  "./components/mockups/dashboard-redesign/PriorityCardGrid.tsx": () => import("../components/mockups/dashboard-redesign/PriorityCardGrid.tsx")
};
