import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getAlerts } from "../api/alerts";
import { closePurchase } from "../api/purchases";
import { useLocation } from "../context/LocationContext";
import type { AlertsResponse, AwaitingReceivingAlert, BelowParAlert, CriticalStockAlert, ExpiryAlert, ReplenishmentAlert, ReorderDueAlert } from "../types";
import { formatQuantityWithUnit } from "../utils/purchaseUnits";
import "./AlertsPage.css";

type Filter = "all" | "urgent" | "order" | "receive" | "expiry";
type GroupTone = "red" | "amber" | "purple" | "orange" | "blue";
const EMPTY_ALERTS: AlertsResponse = { lowStock: [], critical: [], reorderDue: [], belowPar: [], awaitingReceiving: [], replenishmentAlerts: [], expiringSoon: [], expired: [] };
const fmtDate = (value: string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(value));
function daysUntil(value: string) { const today = new Date(); today.setHours(0,0,0,0); const target = new Date(value); target.setHours(0,0,0,0); return Math.round((target.getTime()-today.getTime())/86400000); }
function timeAgo(date: Date) { const seconds = Math.max(0, Math.round((Date.now()-date.getTime())/1000)); if(seconds<60)return "just now"; if(seconds<3600)return `${Math.floor(seconds/60)}m ago`; return `${Math.floor(seconds/3600)}h ago`; }

export function AlertsPage() {
  const { activeLocationId } = useLocation();
  const [alerts,setAlerts] = useState<AlertsResponse>(EMPTY_ALERTS);
  const [loading,setLoading] = useState(true); const [refreshing,setRefreshing] = useState(false); const [error,setError] = useState<string|null>(null); const [lastRefreshed,setLastRefreshed] = useState<Date|null>(null);
  const [filter,setFilter] = useState<Filter>("all"); const [search,setSearch] = useState("");
  const [openGroups,setOpenGroups] = useState<Record<string,boolean>>({critical:true,replenishment:true,reorder:false,receiving:true,expired:true,expiring:false,belowPar:false});
  const load = useCallback(async(refresh=false)=>{ refresh?setRefreshing(true):setLoading(true); setError(null); try{setAlerts(await getAlerts());setLastRefreshed(new Date());}catch(err){setError(err instanceof Error?err.message:"Failed to load alerts");}finally{setLoading(false);setRefreshing(false);}},[]);
  useEffect(()=>{void load();},[activeLocationId,load]);
  const counts = useMemo(()=>{const critical=alerts.critical.length,order=alerts.reorderDue.length+alerts.belowPar.length+(alerts.replenishmentAlerts??[]).length,receive=alerts.awaitingReceiving.length,expiry=alerts.expiringSoon.length+alerts.expired.length;return{critical,order,receive,expiry,total:critical+order+receive+expiry};},[alerts]);
  const query=search.trim().toLowerCase(); const matches=(name:string)=>!query||name.toLowerCase().includes(query); const toggle=(key:string)=>setOpenGroups(prev=>({...prev,[key]:!prev[key]}));
  if(loading)return <div className="page-loading"><div className="spinner"/><p>Checking inventory…</p></div>;
  if(error)return <div className="page-error"><div className="alert alert--error">{error}</div></div>;
  const groups=[
    {key:"critical",filter:"urgent" as Filter,title:"Critical stock",tone:"red" as GroupTone,hint:"Act now to avoid missed sales or service interruptions.",count:alerts.critical.length,action:<Link to="/reorder-suggestions">Create purchase draft</Link>,content:<CriticalRows items={alerts.critical.filter(i=>matches(i.itemName))}/>},
    {key:"replenishment",filter:"order" as Filter,title:"Order now",tone:"amber" as GroupTone,hint:"ShelfSense has identified stock that needs replenishment.",count:(alerts.replenishmentAlerts??[]).length,action:<Link to="/reorder-suggestions">Review reorder</Link>,content:<ReplenishmentRows items={(alerts.replenishmentAlerts??[]).filter(i=>matches(i.itemName))}/>},
    {key:"reorder",filter:"order" as Filter,title:"Procurement due",tone:"amber" as GroupTone,hint:"Items that reached or passed their buying cycle.",count:alerts.reorderDue.length,action:<Link to="/reorder-suggestions">Review reorder</Link>,content:<ReorderRows items={alerts.reorderDue.filter(i=>matches(i.itemName))}/>},
    {key:"receiving",filter:"receive" as Filter,title:"Waiting to receive",tone:"purple" as GroupTone,hint:"Open purchase orders with stock still pending.",count:alerts.awaitingReceiving.length,action:<Link to="/purchases">View purchase orders</Link>,content:<ReceivingRows items={alerts.awaitingReceiving.filter(i=>matches(i.itemName))} onClosed={()=>load()}/>},
    {key:"expired",filter:"expiry" as Filter,title:"Expired stock",tone:"red" as GroupTone,hint:"Remove or review these batches immediately.",count:alerts.expired.length,content:<ExpiryRows items={alerts.expired.filter(i=>matches(i.item.name))} expired/>},
    {key:"expiring",filter:"expiry" as Filter,title:"Expiring soon",tone:"orange" as GroupTone,hint:"Prioritize use, promotion, transfer, or disposal planning.",count:alerts.expiringSoon.length,content:<ExpiryRows items={alerts.expiringSoon.filter(i=>matches(i.item.name))}/>},
    {key:"belowPar",filter:"order" as Filter,title:"Below target",tone:"blue" as GroupTone,hint:"Lower-priority items below their preferred stock level.",count:alerts.belowPar.length,action:<Link to="/reorder-suggestions">Review items</Link>,content:<BelowParRows items={alerts.belowPar.filter(i=>matches(i.itemName))}/>},
  ].filter(g=>g.count>0&&(filter==="all"||g.filter===filter));
  return <main className="action-center">
    <header className="action-center__header"><div><div className="action-center__eyebrow"><span className="action-center__eyebrow-dot"/>Action center</div><h1>Needs attention</h1><p className="action-center__subtitle">{counts.total===0?"Inventory looks healthy. No action is required right now.":`${counts.total} item${counts.total===1?"":"s"} need a decision or action.`}</p></div><div className="action-center__header-actions">{lastRefreshed&&<span className="action-center__updated">Updated {timeAgo(lastRefreshed)}</span>}<button className="action-center__refresh" type="button" disabled={refreshing} onClick={()=>void load(true)}><span className={refreshing?"action-center__spin":""}>↻</span> {refreshing?"Refreshing":"Refresh"}</button>{counts.order+counts.critical>0&&<Link className="action-center__primary" to="/reorder-suggestions">Create purchase draft</Link>}</div></header>
    <section className="action-center__summary" aria-label="Alert summary"><SummaryCard label="Critical now" value={counts.critical} icon="!" tone="red" active={filter==="urgent"} onClick={()=>setFilter(filter==="urgent"?"all":"urgent")}/><SummaryCard label="Need ordering" value={counts.order} icon="↓" tone="amber" active={filter==="order"} onClick={()=>setFilter(filter==="order"?"all":"order")}/><SummaryCard label="Waiting to receive" value={counts.receive} icon="→" tone="purple" active={filter==="receive"} onClick={()=>setFilter(filter==="receive"?"all":"receive")}/><SummaryCard label="Expiry action" value={counts.expiry} icon="◷" tone="slate" active={filter==="expiry"} onClick={()=>setFilter(filter==="expiry"?"all":"expiry")}/></section>
    {counts.total===0?<div className="action-center__empty"><div className="action-center__empty-icon">✓</div><h2>Inventory looks healthy</h2><p>No urgent stock, purchase, or expiry actions are waiting.</p></div>:<><div className="action-center__toolbar"><div className="action-center__filters">{(["all","urgent","order","receive","expiry"] as Filter[]).map(item=><button key={item} className={`action-filter ${filter===item?"action-filter--active":""}`} onClick={()=>setFilter(item)} type="button">{{all:"All actions",urgent:"Critical",order:"Order",receive:"Receive",expiry:"Expiry"}[item]}</button>)}</div><label className="action-center__search"><span>⌕</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search items"/></label></div><div className="action-groups">{groups.map(group=><ActionGroup key={group.key} title={group.title} hint={group.hint} count={group.count} tone={group.tone} open={Boolean(openGroups[group.key])} onToggle={()=>toggle(group.key)} action={group.action}>{group.content}</ActionGroup>)}{groups.length===0&&<div className="action-center__no-match">No actions match this filter.</div>}</div></>}
  </main>;
}
function SummaryCard({label,value,icon,tone,active,onClick}:{label:string;value:number;icon:string;tone:"red"|"amber"|"purple"|"slate";active:boolean;onClick:()=>void}){return <button type="button" className={`action-summary ${active?"action-summary--active":""}`} onClick={onClick}><span className={`action-summary__icon action-summary__icon--${tone}`}>{icon}</span><span><span className="action-summary__label">{label}</span><strong className="action-summary__value">{value}</strong></span></button>}
function ActionGroup({title,hint,count,tone,open,onToggle,action,children}:{title:string;hint:string;count:number;tone:GroupTone;open:boolean;onToggle:()=>void;action?:React.ReactNode;children:React.ReactNode}){return <section className="action-group"><button type="button" className="action-group__header" onClick={onToggle}><span className="action-group__title-wrap"><span className={`action-group__marker action-group__marker--${tone}`}/><span><span className="action-group__title">{title}</span><span className="action-group__hint">{hint}</span></span></span><span className="action-group__right"><span className="action-group__count">{count}</span>{action&&<span className="action-group__cta" onClick={e=>e.stopPropagation()}>{action}</span>}<span className={`action-group__chevron ${open?"action-group__chevron--open":""}`}>⌄</span></span></button>{open&&<div className="action-list">{children}</div>}</section>}
function Row({name,meta,label1,value1,valueTone,label2,value2,action,secondary}:{name:string;meta?:string;label1:string;value1:string;valueTone?:"danger"|"warn";label2?:string;value2?:string;action:React.ReactNode;secondary?:React.ReactNode}){return <div className="action-row"><div><div className="action-row__name">{name}</div>{meta&&<div className="action-row__meta">{meta}</div>}{secondary}</div><div className="action-row__metric"><div className="action-row__metric-label">{label1}</div><div className={`action-row__metric-value ${valueTone?`action-row__metric-value--${valueTone}`:""}`}>{value1}</div></div>{label2&&<div className="action-row__metric"><div className="action-row__metric-label">{label2}</div><div className="action-row__metric-value">{value2}</div></div>}<div>{action}</div></div>}
function CriticalRows({items}:{items:CriticalStockAlert[]}){if(!items.length)return <NoRows/>;return <>{[...items].sort((a,b)=>a.quantity-b.quantity).map(item=><Row key={item.itemId} name={item.itemName} meta={item.quantity===0?"Out of stock":`Critical level: ${formatQuantityWithUnit(item.criticalStockLevel,item.unit)}`} label1="Available" value1={formatQuantityWithUnit(item.quantity,item.unit)} valueTone="danger" label2="What to do" value2={item.activePo?"Receive existing PO":"Create purchase order"} action={<Link className="action-row__button action-row__button--primary" to={item.activePo?`/purchases/${item.activePo.purchaseId}`:"/reorder-suggestions"}>{item.activePo?"View PO":"Reorder"}</Link>}/>)}</>}
function ReplenishmentRows({items}:{items:ReplenishmentAlert[]}){if(!items.length)return <NoRows/>;return <>{items.map(item=>{const r=item.replenishment,suggested=r.suggestedBuyingQty??r.additionalSuggestedBuyingQty??0,unit=item.purchaseUnit??item.unit;return <Row key={`${item.itemId}-${r.status}`} name={item.itemName} meta={r.statusLabel} label1="Available" value1={formatQuantityWithUnit(item.quantity,item.unit)} valueTone="warn" label2="Suggested order" value2={suggested>0?formatQuantityWithUnit(suggested,unit,0):"Review setup"} action={<Link className="action-row__button action-row__button--primary" to={r.status==="CONFIGURATION_REQUIRED"?`/items?q=${encodeURIComponent(item.itemName)}`:"/reorder-suggestions"}>{r.status==="CONFIGURATION_REQUIRED"?"Fix setup":"Reorder"}</Link>}/>})}</>}
function ReorderRows({items}:{items:ReorderDueAlert[]}){if(!items.length)return <NoRows/>;return <>{[...items].sort((a,b)=>b.daysOverdue-a.daysOverdue).map(item=><Row key={item.itemId} name={item.itemName} meta={item.daysOverdue>0?`${item.daysOverdue} days overdue`:"Due today"} label1="Available" value1={formatQuantityWithUnit(item.quantity,item.unit)} valueTone="warn" label2="Target" value2={item.parStockLevel!=null?formatQuantityWithUnit(item.parStockLevel,item.unit):"Not set"} action={<Link className="action-row__button action-row__button--primary" to="/reorder-suggestions">Review order</Link>}/>)}</>}
function ReceivingRows({items,onClosed}:{items:AwaitingReceivingAlert[];onClosed:()=>Promise<void>}){const[closing,setClosing]=useState<string|null>(null);if(!items.length)return <NoRows/>;return <>{items.map(item=><Row key={`${item.purchaseId}-${item.itemId}`} name={item.itemName} meta={`PO ${item.poReference}${item.expectedDeliveryDate?` · expected ${fmtDate(item.expectedDeliveryDate)}`:""}`} label1="Pending" value1={formatQuantityWithUnit(item.pendingQty,item.unit)} valueTone="warn" label2="Received" value2={formatQuantityWithUnit(item.receivedQty,item.unit)} action={<><Link className="action-row__button action-row__button--primary" to={`/purchases/${item.purchaseId}`}>Receive stock</Link><button type="button" className="action-row__close" disabled={closing===item.purchaseId} onClick={async()=>{if(!window.confirm("Close this purchase order?"))return;setClosing(item.purchaseId);try{await closePurchase(item.purchaseId);await onClosed()}finally{setClosing(null)}}}>{closing===item.purchaseId?"Closing…":"Close PO"}</button></>}/>)}</>}
function ExpiryRows({items,expired=false}:{items:ExpiryAlert[];expired?:boolean}){if(!items.length)return <NoRows/>;return <>{[...items].sort((a,b)=>new Date(a.expiryDate).getTime()-new Date(b.expiryDate).getTime()).map(batch=>{const days=daysUntil(batch.expiryDate),urgency=expired?`${Math.abs(days)} days expired`:days===0?"Expires today":`${days} days left`;return <Row key={batch.id} name={batch.item.name} meta={batch.batchNo?`Batch ${batch.batchNo}`:"Batch number not available"} label1="Quantity" value1={formatQuantityWithUnit(batch.remainingQuantity,batch.item.unit)} valueTone={expired||days<=3?"danger":"warn"} label2="Expiry" value2={`${fmtDate(batch.expiryDate)} · ${urgency}`} action={<Link className="action-row__button" to="/inventory">View batches</Link>}/>})}</>}
function BelowParRows({items}:{items:BelowParAlert[]}){if(!items.length)return <NoRows/>;return <>{items.map(item=><Row key={item.itemId} name={item.itemName} meta="Below preferred stock level" label1="Available" value1={formatQuantityWithUnit(item.quantity,item.unit)} label2="Gap to target" value2={formatQuantityWithUnit(Math.max(0,item.parStockLevel-item.quantity),item.unit)} action={<Link className="action-row__button" to="/reorder-suggestions">Review</Link>}/>)}</>}
function NoRows(){return <div className="action-center__no-match">No matching items in this section.</div>}
