// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env["DATABASE_URL"] ??
  "postgresql://postgres:postgres@localhost:5432/shelfsense?schema=public";

// DIRECT_URL must be the non-pooled Neon connection string.
// Prisma uses directUrl for `prisma migrate deploy` (DDL statements that
// cannot run through pgBouncer) and the regular url for runtime queries.
// In local dev without a pooler, fall back to DATABASE_URL.
const directUrl = process.env["DIRECT_URL"] ?? databaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
    directUrl,
  },
});
